name: iapp
description: App powered by IA to classifie art pieces in historical epochs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6 
  sqflite: ^2.0.0+4
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  path_provider: ^2.0.9
  camera: ^0.9.4+5
  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.0.6
  back_button_interceptor: ^7.0.3
  image_picker: ^1.1.1
  animations: ^2.0.0
  animated_list: ^0.0.4
  carousel_slider: ^4.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/background/
    - assets/images/profile/
    - assets/images/bd/barroco/Artemisia Gentileschi/
    - assets/images/bd/barroco/Caravaggio/
    - assets/images/bd/barroco/Diego Velazquez/
    - assets/images/bd/barroco/Georges de La Tour/
    - assets/images/bd/barroco/Rembrandt van Rijn/
    - assets/images/bd/cubismo/Fernand Léger/
    - assets/images/bd/cubismo/Georges Braque/
    - assets/images/bd/cubismo/Juan Gris/
    - assets/images/bd/cubismo/Pablo Picasso/
    - assets/images/bd/expresionismo/Alexej von Jawlensky/
    - assets/images/bd/expresionismo/Edvard Munch/
    - assets/images/bd/expresionismo/Emil Nolde/
    - assets/images/bd/expresionismo/Ernst Ludwig Kirchner/
    - assets/images/bd/expresionismo/Lyonel Feininger/
    - assets/images/bd/expresionismo/Vincent van Gogh/
    - assets/images/bd/expresionismo/Wassily Kandinsky/
    - assets/images/bd/impresionismo/Claude Monet/
    - assets/images/bd/impresionismo/Edgar Degas/
    - assets/images/bd/impresionismo/Pierre-Auguste Renoir/
    - assets/images/bd/impresionismo/Vincent van Gogh/
    - assets/images/bd/realismo/Gustave Courbet/
    - assets/images/bd/realismo/Jean-François Millet/
    - assets/images/bd/realismo/Jean-Honore Fragonard/
    - assets/images/bd/realismo/Johannes Vermeer/
    - assets/images/bd/renacimiento/El bosco/
    - assets/images/bd/renacimiento/Leonardo da Vinci/
    - assets/images/bd/renacimiento/Miguel Angel/
    - assets/images/bd/renacimiento/Rafael Sanzio/
    - assets/images/bd/renacimiento/Sandro Botticelli/
    - assets/images/bd/rococo/Francisco de Goya/
    - assets/images/bd/rococo/François Boucher/
    - assets/images/bd/rococo/Jean-Antoine Watteau/
    - assets/images/bd/rococo/Jean-Honoré Fragonard/
    - assets/images/bd/romanticismo/Caspar David Friedrich/
    - assets/images/bd/romanticismo/Eugene Delacroix/
    - assets/images/bd/romanticismo/Francisco de Goya/
    - assets/images/bd/romanticismo/Jacques-Louis David/
    - assets/images/bd/romanticismo/Theodore Gericault/
    - assets/images/bd/romanticismo/William Turner/
    - assets/images/museos/
    - assets/images/museos/descripciones.json
    - assets/images/museos/Acrópolis-Atenas-Grecia/
    - assets/images/museos/Louvre-Paris-Francia/
    - assets/images/museos/Museo Británico-Londres-Inglaterra/
    - assets/images/museos/Museo del Prado-Madrid-España/
    - assets/images/museos/Museo Metropolitano de Arte-Nueva York-Estados Unidos/
    - assets/images/museos/State Hermitage-San Petersburgo-Rusia/
  fonts:
    - family: EdensorTittle
      fonts:
        - asset: assets/fonts/edensor_tittle.otf
    - family: RalewayExtraLight
      fonts:
        - asset: assets/fonts/raleway_extralight.ttf
    - family: RalewayMedium
      fonts:
        - asset: assets/fonts/raleway_medium.ttf
    - family: Themunday
      fonts:
        - asset: assets/fonts/themunday.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf


